### ISSUE TITLE
How can I install `utils_misc` package?

### ISSUE THREAD

**Issue by hedonihilist** [tingofurro/summac#1]
Thanks for your work, it's great! But I have some trouble running the example code provided in the README.md.

When I ran the code, the package `utils_misc` is missing and I cannot find the right package used in model_summac.py.

I tried `pip install utils_misc` but obviously that's not the package required.

How can I install `utils_misc` ? Or could you provide a `requirements.txt` file ?

**Comment by tingofurro** [comment]
Hey @hedonihilist ! Thanks for pointing that out... A few utils files were indeed missing and have been now.

Let me know if it still doesn't work!

**Comment by hedonihilist** [comment]
Thanks, it works fine now. :+1:
