### ISSUE TITLE
Which version of QuestEval did you use?

### ISSUE THREAD

**Issue by ryokamoi** [tingofurro/summac#3]
I guess QuestEval implementation by the authors [(repo)](https://github.com/ThomasScialom/QuestEval) is used in this code.
Can I ask which version (commit id) you used for your result?

https://github.com/tingofurro/summac/blob/53fae37bbdd3995c50b50a2713d196680966c765/model_baseline.py#L17

**Comment by tingofurro** [comment]
Hey Ryo,

You are correct, we used the implementation from the official Github repo for the QuestEval comparison: https://github.com/ThomasScialom/QuestEval
I unfortunately don't have access to the machine anymore (the machine I used in Berkeley), but I ran experiment in mid-July, so I asssume from the Github history that it was either version 0.2.0 or 0.2.4.

I would hope however that the results would not be affected by the QuestEval version. Are you noticing discrepancies?

**Comment by ryokamoi** [comment]
Hi Laban,

Thank you for your kind reply!
Honestly, I have not tried your code yet.

However, the README of the QuestEval repository says `the code has changed from the paper` and I observed some differences from the older version.
[https://github.com/ThomasScialom/QuestEval/blob/main/README.md#summarization](https://github.com/ThomasScialom/QuestEval/blob/main/README.md#summarization)

I will try on 0.2.0 or 0.2.4 to reproduce your results.
